"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { 
  Check, 
  Copy, 
  Download, 
  Loader2, 
  Share2, 
  Twitter, 
  Linkedin, 
  Facebook 
} from "lucide-react"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { toJpeg } from "html-to-image"

export default function ShareStackButton({ userId, userName }: { userId: string, userName: string }) {
  const [copied, setCopied] = useState(false)
  const [downloading, setDownloading] = useState(false)
  const [shareUrl, setShareUrl] = useState("")

  // 1. Construct URL - Fetch username to use in URL, fallback to userId if no username
  useEffect(() => {
    const fetchUsername = async () => {
      try {
        const { createClient } = await import("@/utils/supabase/client")
        const supabase = createClient()
        const { data: profile } = await supabase
          .from("profiles")
          .select("username")
          .eq("user_id", userId)
          .maybeSingle()
        
        const username = profile?.username || userId
        setShareUrl(`${window.location.origin}/u/${username}`)
      } catch (error) {
        // Fallback to userId if fetch fails
        setShareUrl(`${window.location.origin}/u/${userId}`)
      }
    }
    fetchUsername()
  }, [userId])



  // 2. Copy Logic
  const handleCopyLink = () => {
    navigator.clipboard.writeText(shareUrl)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  // 3. Download Image Logic (Your existing logic)
  const handleDownloadImage = async () => {
    const element = document.getElementById("stack-capture")
    if (!element) return

    setDownloading(true)
    
    try {
      const filter = (node: HTMLElement) => {
        const exclusionClasses = ['hide-on-export']
        return !exclusionClasses.some((classname) => node.classList?.contains(classname))
      }

      const dataUrl = await toJpeg(element, { 
        quality: 0.95, 
        backgroundColor: '#ffffff', 
        filter: filter as any, 
        pixelRatio: 2 
      })

      const link = document.createElement("a")
      link.download = `${userName.replace(/\s+/g, '-').toLowerCase()}-stack.jpg`
      link.href = dataUrl
      link.click()

    } catch (error) {
      console.error("Failed to generate image", error)
    } finally {
      setDownloading(false)
    }
  }

  // 4. Social Links Generators
  const shareText = `Check out ${userName}'s AI Stack! Generated by AI Stack Builder.`
  const socials = [
    {
      icon: <Twitter className="w-4 h-4" />,
      label: "X (Twitter)",
      href: `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`
    },
    {
      icon: <Linkedin className="w-4 h-4" />,
      label: "LinkedIn",
      href: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`
    },
    {
      icon: <Facebook className="w-4 h-4" />,
      label: "Facebook",
      href: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}`
    }
  ]

  return (
    <Dialog>
      {/* THE TRIGGER BUTTON (Visible on Page) */}
      <DialogTrigger asChild>
        <Button className="gap-2 rounded-full bg-black text-white hover:bg-zinc-800 shadow-md">
          <Share2 className="w-4 h-4" /> Share Stack
        </Button>
      </DialogTrigger>

      {/* THE POPUP CONTENT */}
      <DialogContent className="sm:max-w-md bg-white">
        <DialogHeader>
          <DialogTitle>Share Public Link</DialogTitle>
          <DialogDescription>
            Share this stack with the world or download it as an image.
          </DialogDescription>
        </DialogHeader>

        <div className="flex flex-col gap-6 py-4">
          
          {/* A. Copy Link Section (ChatGPT Style) */}
          <div className="space-y-2">
            <Label htmlFor="link" className="text-xs font-semibold text-zinc-500">
              PUBLIC LINK
            </Label>
            <div className="flex items-center gap-2">
              <div className="relative flex-1">
                <Input 
                  id="link" 
                  defaultValue={shareUrl} 
                  readOnly 
                  className="pr-10 bg-zinc-50 border-zinc-200 text-zinc-600 h-10" 
                />
              </div>
              <Button 
                type="button" 
                size="icon" 
                onClick={handleCopyLink}
                className={copied ? "bg-green-600 hover:bg-green-700" : "bg-zinc-900"}
              >
                {copied ? <Check className="h-4 w-4 text-white" /> : <Copy className="h-4 w-4" />}
              </Button>
            </div>
          </div>

          {/* B. Social Media Row */}
          <div className="space-y-2">
             <Label className="text-xs font-semibold text-zinc-500">SHARE TO SOCIAL</Label>
             <div className="grid grid-cols-3 gap-2">
               {socials.map((s) => (
                 <a 
                   key={s.label} 
                   href={s.href} 
                   target="_blank" 
                   rel="noreferrer" 
                   className="w-full"
                 >
                   <Button variant="outline" className="w-full gap-2 text-xs border-zinc-200 hover:bg-zinc-50">
                     {s.icon} {s.label}
                   </Button>
                 </a>
               ))}
             </div>
          </div>

          {/* C. Download Image Button */}
          <div className="space-y-2">
             <Label className="text-xs font-semibold text-zinc-500">EXPORT</Label>
             <Button 
                onClick={handleDownloadImage} 
                variant="outline"
                className="w-full gap-2 border-dashed border-zinc-300 hover:bg-zinc-50 h-12"
                disabled={downloading}
              >
                {downloading ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" /> Generating Image...
                  </>
                ) : (
                  <>
                    <Download className="w-4 h-4" /> Download High-Res Image (JPG)
                  </>
                )}
              </Button>
          </div>

        </div>
      </DialogContent>
    </Dialog>
  )
}