"use server"

import { createClient } from "@/utils/supabase/server"
import { revalidatePath } from "next/cache"
import OpenAI from "openai"
import { ensureProfile } from "@/actions/profiles"

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
})

export interface GeneratePathInput {
  currentRole: string
  bioContext: string
  mainGoal: string
}

export interface GeneratePathResult {
  success: boolean
  error?: string
  pathId?: string
}

export async function generatePath(
  data: GeneratePathInput
): Promise<GeneratePathResult> {
  console.log("🚀 STARTING GENERATE PATH...")

  try {
    const supabase = await createClient()

    // 1. Ensure profile exists with username (includes auth verification and retry logic)
    const profileResult = await ensureProfile()
    if (!profileResult.success) {
      return { success: false, error: profileResult.error || "Failed to ensure profile" }
    }

    // 2. Get authenticated user for path creation
    const { data: { user }, error: userError } = await supabase.auth.getUser()
    if (userError || !user) {
      console.error("❌ User Auth Failed")
      return { success: false, error: "User not authenticated" }
    }

    // 2. Create a new path record with slug = null and 'Untitled Path' title
    // The slug will be generated by n8n webhook when path_title is provided
    const { data: newPath, error: pathCreateError } = await supabase
      .from("upgrade_paths")
      .insert({
        user_id: user.id,
        role: data.currentRole,
        main_goal: data.mainGoal,
        context: data.bioContext,
        path_title: "Untitled Path", // Initial placeholder title
        slug: null, // Slug will be set by n8n webhook when path_title is ready
        efficiency_audit: null,
        ai_tools: null,
        human_courses: null,
        immediate_steps: null,
      })
      .select("id")
      .single()

    if (pathCreateError || !newPath) {
      console.error("❌ Failed to create path record:", pathCreateError)
      return { success: false, error: "Failed to create path" }
    }

    const pathId = newPath.id
    console.log(`✅ Created path record with ID: ${pathId}`)

    // Fetch the path record to use its data for matching
    const { data: pathRecord, error: pathFetchError } = await supabase
      .from("upgrade_paths")
      .select("role, main_goal, context")
      .eq("id", pathId)
      .single()

    if (pathFetchError || !pathRecord) {
      console.error("❌ Failed to fetch path record:", pathFetchError)
      return { success: false, error: "Failed to fetch path record" }
    }

    // =========================================================
    // 🧠 DATABASE MATCHING (FILTERS ENABLED)
    // =========================================================
    let verifiedTools: any[] = []
    let verifiedCourses: any[] = []

    try {
      // Use the path record's data for embedding (role, main_goal, context from upgrade_paths)
      const embeddingInput = `${pathRecord.role} ${pathRecord.main_goal} ${pathRecord.context}`
      console.log(`🔎 Generating embedding from path record: "${pathRecord.role}"`)
      
      const embeddingResponse = await openai.embeddings.create({
        model: "text-embedding-3-small",
        input: embeddingInput,
      })
      const userVector = embeddingResponse.data[0].embedding

      // SEARCH TOOLS (Strict Filter: ai_tool)
      const { data: tools, error: toolError } = await supabase.rpc("match_resources", {
        query_embedding: userVector,
        match_threshold: 0.1, // Keep this low to ensure matches
        match_count: 3,       // Get top 3
        min_machine_score: 1,
        min_human_score: 0,
        filter_type: "ai_tool" 
      })

      if (toolError) {
        console.error("❌ DB Tool Error:", toolError)
      } else if (tools) {
        console.log(`✅ VERIFIED TOOLS:`, tools.map((t: any) => t.name))
        verifiedTools = tools
      }

      // SEARCH COURSES (Strict Filter: human_course)
      const { data: courses, error: courseError } = await supabase.rpc("match_resources", {
        query_embedding: userVector,
        match_threshold: 0.1,
        match_count: 3,
        min_machine_score: 0,
        min_human_score: 1,
        filter_type: "human_course"
      })

      if (courseError) {
        console.error("❌ DB Course Error:", courseError)
      } else if (courses) {
        console.log(`✅ VERIFIED COURSES:`, courses.map((c: any) => c.name))
        verifiedCourses = courses
      }

    } catch (err) {
      console.error("⚠️ Matching Logic Crash:", err)
    }

    // =========================================================
    // 💾 SAVE MATCHES TO PATH RECORD
    // =========================================================
    const { error: updateError } = await supabase
      .from("upgrade_paths")
      .update({
        ai_tools: verifiedTools,
        human_courses: verifiedCourses,
      })
      .eq("id", pathId)

    if (updateError) {
      console.error("❌ Failed to save matches to path:", updateError)
      // Continue execution - matches will still be sent to n8n
    } else {
      console.log(`✅ Saved ${verifiedTools.length} tools and ${verifiedCourses.length} courses to path ${pathId}`)
    }

    // =========================================================
    // 💾 INSERT INTO path_resources TABLE
    // =========================================================
    // Insert ai_tools into path_resources with status 'suggested'
    if (verifiedTools.length > 0) {
      const toolInserts = verifiedTools
        .map((tool: any) => ({
          path_id: pathId,
          resource_id: tool.id,
          status: "suggested",
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString()
        }))
        .filter((item: any) => item.resource_id) // Only include items with resource_id

      if (toolInserts.length > 0) {
        const { error: toolsError } = await supabase
          .from("path_resources")
          .upsert(toolInserts, {
            onConflict: "path_id,resource_id",
            ignoreDuplicates: false
          })

        if (toolsError) {
          console.error("❌ Failed to insert ai_tools into path_resources:", toolsError)
        } else {
          console.log(`✅ Inserted ${toolInserts.length} tools into path_resources`)
        }
      }
    }

    // Insert human_courses into path_resources with status 'suggested'
    if (verifiedCourses.length > 0) {
      const courseInserts = verifiedCourses
        .map((course: any) => ({
          path_id: pathId,
          resource_id: course.id,
          status: "suggested",
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString()
        }))
        .filter((item: any) => item.resource_id) // Only include items with resource_id

      if (courseInserts.length > 0) {
        const { error: coursesError } = await supabase
          .from("path_resources")
          .upsert(courseInserts, {
            onConflict: "path_id,resource_id",
            ignoreDuplicates: false
          })

        if (coursesError) {
          console.error("❌ Failed to insert human_courses into path_resources:", coursesError)
        } else {
          console.log(`✅ Inserted ${courseInserts.length} courses into path_resources`)
        }
      }
    }

    // =========================================================
    // 🚀 SEND TO N8N
    // =========================================================
    const webhookUrl = process.env.NEXT_PUBLIC_N8N_WEBHOOK
    
    if (!webhookUrl) {
      console.error("❌ CRITICAL ERROR: Webhook URL missing")
      return { success: false, error: "Configuration Error" }
    }

    // LOG WHAT WE ARE SENDING
    console.log(`📦 Sending Payload to n8n...`)
    console.log(`   - Tools: ${verifiedTools.length}`)
    console.log(`   - Courses: ${verifiedCourses.length}`)

    const response = await fetch(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        user_id: user.id,
        path_id: pathId,
        ...data,
        verified_matches: {
          tools: verifiedTools,
          courses: verifiedCourses
        }
      }),
    })

    if (!response.ok) {
      console.error(`❌ n8n Error: ${response.status}`)
      return { success: false, error: "AI Agent refused connection" }
    }
    
    console.log("✅ SUCCESS: Data sent to n8n!")
    revalidatePath("/")
    // Return only pathId - slug will be ready after n8n processes
    // Frontend will poll for the final slug
    return { success: true, pathId }
    
  } catch (error) {
    console.error("❌ CRASH:", error)
    return { success: false, error: "An unexpected error occurred" }
  }
}